"""
Node 7: Generate Incident Summary.
Synthesizes the complete reasoning chain into a concise summary.
"""

from __future__ import annotations

from typing import Any, Dict
from app.ai.state import IncidentAnalysisState


def generate_incident_summary(state: IncidentAnalysisState) -> Dict[str, Any]:
    """
    Produce reasoning summary and final summary for UI and notification.
    """
    # Check LLM summary first
    raw = state.get("raw_llm_output")
    llm_summary = raw.get("reasoning_summary") or raw.get("summary") if raw else None

    severity = state.get("assessed_severity", "WARNING")
    hostname = state.get("hostname") or state.get("host") or "unknown"
    affected = ", ".join(sorted(state.get("affected_metrics", [])))
    source = state.get("analysis_source", "rule_engine")
    source_label = "Groq LLM" if source == "groq" else "Rule Engine"

    if llm_summary and len(llm_summary.strip()) > 20:
        final_summary = llm_summary.strip()
    else:
        cause = state.get("probable_cause", "Resource saturation")
        final_summary = (
            f"[{severity}] Incident on {hostname} affecting {affected}. "
            f"{cause} Analysis generated by {source_label}."
        )

    return {
        "reasoning_summary": final_summary,
        "final_summary": final_summary,
    }
