"""
Initial database migration — creates all tables.

Generated by Alembic autogenerate from the SQLAlchemy models.
Run with: alembic upgrade head
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- metrics ----
    op.create_table(
        "metrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("hostname", sa.String(255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cpu_usage", sa.Float(), nullable=False),
        sa.Column("memory_usage", sa.Float(), nullable=False),
        sa.Column("disk_usage", sa.Float(), nullable=False),
        sa.Column("load_1m", sa.Float(), nullable=False),
        sa.Column("load_5m", sa.Float(), nullable=False),
        sa.Column("load_15m", sa.Float(), nullable=False),
        sa.Column("cpu_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("memory_available_mb", sa.Float(), nullable=True),
        sa.Column("disk_free_gb", sa.Float(), nullable=True),
        sa.Column("network_rx_bytes", sa.BigInteger(), nullable=True),
        sa.Column("network_tx_bytes", sa.BigInteger(), nullable=True),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("os_name", sa.String(255), nullable=True),
        sa.Column("kernel_version", sa.String(255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_metrics_hostname", "metrics", ["hostname"])
    op.create_index("ix_metrics_timestamp", "metrics", ["timestamp"])
    op.create_index("ix_metrics_hostname_timestamp", "metrics", ["hostname", "timestamp"])

    # ---- process_snapshots ----
    op.create_table(
        "process_snapshots",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("metric_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("metrics.id", ondelete="CASCADE"), nullable=False),
        sa.Column("process_name", sa.String(255), nullable=False),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("memory_percent", sa.Float(), nullable=True),
        sa.Column("snapshot_type", sa.String(50), nullable=False, server_default="top_cpu"),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_process_snapshots_metric_id", "process_snapshots", ["metric_id"])

    # ---- anomalies ----
    op.create_table(
        "anomalies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("metric_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("metrics.id", ondelete="CASCADE"), nullable=False),
        sa.Column("metric_name", sa.String(50), nullable=False),
        sa.Column("observed_value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("anomaly_type", sa.String(50), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("description", sa.String(500), nullable=False),
        sa.Column("is_persistent", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("consecutive_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_anomalies_metric_id", "anomalies", ["metric_id"])
    op.create_index("ix_anomalies_detected_at", "anomalies", ["detected_at"])
    op.create_index("ix_anomalies_severity", "anomalies", ["severity"])
    op.create_index("ix_anomalies_metric_name", "anomalies", ["metric_name"])

    # ---- incidents ----
    op.create_table(
        "incidents",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("incident_key", sa.String(255), nullable=False, unique=True),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="OPEN"),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("hostname", sa.String(255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("probable_cause", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("correlation_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("affected_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("llm_confidence", sa.Float(), nullable=True),
        sa.Column("llm_analyzed", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("observation_count", sa.Integer(), nullable=False, server_default="1"),
    )
    op.create_index("ix_incidents_status", "incidents", ["status"])
    op.create_index("ix_incidents_severity", "incidents", ["severity"])
    op.create_index("ix_incidents_hostname", "incidents", ["hostname"])
    op.create_index("ix_incidents_started_at", "incidents", ["started_at"])
    op.create_index("ix_incidents_incident_key", "incidents", ["incident_key"])

    # ---- incident_anomalies ----
    op.create_table(
        "incident_anomalies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("anomaly_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("anomalies.id", ondelete="CASCADE"), nullable=False),
        sa.Column("linked_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_incident_anomalies_incident_id", "incident_anomalies", ["incident_id"])
    op.create_index("ix_incident_anomalies_anomaly_id", "incident_anomalies", ["anomaly_id"])

    # ---- incident_analyses ----
    op.create_table(
        "incident_analyses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("incident_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("affected_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("probable_causes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recommended_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning_summary", sa.Text(), nullable=True),
        sa.Column("analysis_source", sa.String(20), nullable=False, server_default="rule_based"),
        sa.Column("model_name", sa.String(100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_llm_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_incident_analyses_incident_id", "incident_analyses", ["incident_id"])


def downgrade() -> None:
    op.drop_table("incident_analyses")
    op.drop_table("incident_anomalies")
    op.drop_table("incidents")
    op.drop_table("anomalies")
    op.drop_table("process_snapshots")
    op.drop_table("metrics")
